# Generated by Django 6.0.6 on 2026-06-10 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('sinopsis', models.TextField()),
                ('duracion', models.IntegerField(help_text='Duración en minutos')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Sala 1, Sala 2, etc.', max_length=100)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_asientos', models.IntegerField()),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='user_permissions',
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('precio_entrada', models.DecimalField(decimal_places=2, max_digits=8)),
                ('formato', models.CharField(choices=[('2D', 'Proyección 2D'), ('3D', 'Proyección 3D'), ('4D', 'Proyección 4D')], default='2D', max_length=2)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones', to='tickets.pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('puntuacion', models.IntegerField(help_text='Del 1 al 5')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='tickets.pelicula')),
            ],
        ),
    ]
